---
name: devicemapper weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 3 * * 2
  workflow_dispatch:

jobs:
  # PYTHON CHECKS ON NEXT FEDORA PYTHON AND PYTHON TOOLS VERSION
  next-fedora-python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - dependencies: yamllint
            task: make -f Makefile yamllint
    runs-on: ubuntu-22.04
    container: fedora:41  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
